apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-app
  labels:
    app: diplom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diplom
  template:
    metadata:
      labels:
        app: diplom
    spec:
      containers:
      - name: diplom-container
        image: gcr.io/soy-lore-450513-d6/diplom_aplicate
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
