apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-app
  namespace: diplom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diplom-app
  template:
    metadata:
      labels:
        app: diplom-app
    spec:
      containers:
        - name: diplom-app
          image: gcr.io/soy-lore-450513-d6/diplom_aplicate:latest
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_DB
              value: "mydatabase"
            - name: POSTGRES_USER
              value: "myuser"
            - name: POSTGRES_PASSWORD
              value: "mypassword"
