apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kube-prometheus
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
