apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-app
  labels:
    app: diplom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diplom-app
  template:
    metadata:
      labels:
        app: diplom-app
    spec:
      containers:
        - name: diplom-app
          image: DIPLOM_APPLICATE
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
